angapro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from angaapp.views import*

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('home2/', home2, name='home2'),
    path('affdestination/', affdestination, name='affdestination'),
    path('affheuredp/', affheuredp, name='affheuredp'),
    path('affpays/', affpays, name='affpays'),
    path('addpays/', addpays, name='addpays'),
    path('affeditpays/<int:pays_id>', affeditpays, name='affeditpays'),
    path('updatepays/<int:pays_id>', updatepays, name='updatepays'),
    path('deletepays/<int:pays_id>/', deletepays, name='deletepays'),
    path('affville/', affville, name='affville'),
    path('addville/', addville, name='addville'),
    path('affeditville/<int:ville_id>', affeditville, name='affeditville'),
    path('updateville/<int:ville_id>', updateville, name='updateville'),
    path('deleteville/<int:ville_id>/', deleteville, name='deleteville'),
    path('affkartie/', affkartie, name='affkartie'),
    path('addkartie/', addkarti, name='addkartie'),
    path('deletequartie/<int:quartie_id>/', deletequartie, name='deletequartie'),
    path('updatekartie/<int:quartie_id>/', updatekartie, name='updatekartie'),
    path('affeditquartie/<int:quartie_id>/', affeditquartie, name='affeditquartie'),
    path('addheure/', addheure, name='addheure'),
    path('affligne/', affligne, name='affligne'),
    path('addligne/', addligne, name='addligne'),
    path('deleteligne/<int:ligne_id>/', deleteligne, name='deleteligne'),
    path('affeditligne/<int:ligne_id>/', affeditligne, name='affeditligne'),
    path('deletedepart/<int:time_id>/', deletedepart, name='deletedepart'),
    path('editedepart/<int:time_id>/', editedepart, name='editedepart'),
    path('addepart/', addepart, name='addepart'),
    path('get_depart_options/', get_depart_options, name='get_depart_options'),
    path('affso/>', affso, name='affso'),
    path('addso/>', addso, name='addso'),
    path('affsociete/', affsociete, name='affsociete'),
    path('addsociete/', addsociete, name='addsociete'),
    path('dest/<int:destination_id>', dest, name='dest'),
    path('reserve/<int:societe_id>/', reserve, name='reserve'),
    path('addreserve/<int:societe_id>', addreserve, name='addreserve'),
    path('deleteso/<int:societe_id>', deleteso, name='deleteso'),
    path('affeditso/<int:societe_id>', affeditso, name='affeditso'),
    path('updateso/<int:societe_id>', updateso, name='updateso'),
    path('deletere/<int:reservation_id>', deletere, name='deletere'),
    path('affeditre/<int:reservation_id>', affeditre, name='affeditre'),
    path('updatere/<int:reservation_id>', updatere, name='updatere'),
    path('api/societes/', SocieteListView.as_view(), name='societe-list'),
    path('api/reserve/', ReservationsListView.as_view(), name='reserve-list'),
    path('api/heur/', HeurListView.as_view(), name='heur-list'),
    path('api/destination/', DetinationListView.as_view(), name='destination-list'),
    path('affreserve/',affreserve,name='affreserve'),
    path('affconfirme/<int:reservation_id>',affconfirme,name='affconfirme'),
    path('confirme/<int:reservation_id>',confirme,name='confirme'),
    path('affdest/',affdest,name='affdest'),
    path('affdesti/',affdesti,name='affdesti'),
    path('affavalid<int:ville_id>/',aff_a_valid,name='affavalid'),
    path('affvalid/<int:reservation_id>',affvalid,name='affvalid'),
    path('rejeter/<int:reservation_id>/', rejeter, name='rejeter'),
    path('affichv/<int:confirme_id>',affichv,name='affichv'),
    #path('valide/<int:confirme_id>',valide,name='valide'),
    path('valides/<int:confirme_id>',valides,name='valides'),
    path('affdes/<int:societe_id>',affdes,name='affdes'),
    path('affdes/<int:societe_id>',affdes,name='affdes'),
    path('success/',success,name='success'),
    path('successp/',successp,name='successp'),
    path('mon_vue/',mon_vue,name='mon_vue'),
    #path('recevoirsms/',recevoirsms,name='recevoirsms'),
    #path('api/recevoirsms/', RecevoirSMS.as_view(), name='recevoirsms'),
    path('api/receive_sms/', ReceiveSMSView.as_view(), name='receive_sms'),
    path('api/addreservation/', AddReservationView.as_view(), name='addreservation'),
    path('api/heures_d/', HeureDListCreateView.as_view(), name='heure_d-list-create'),
    path('compte/', include('django.contrib.auth.urls')),
    path('compte/',include('compte.urls')),
    path('load-reserve/',  LoadreserveView.as_view(),name='load-reserve'),
    path('load_societes/',  load_societes,name='load_societes'),
    path('load_quarties/', load_quarties, name='load_quarties'),
    path('load_lignes/', load_lignes, name='load_lignes'),
    path('get_lignes_and_quarties/', get_lignes_and_quarties, name='get_lignes_and_quarties'),
    path('get_time/', get_time, name='get_time'),
    path('confirme_reservation/<int:reservation_id>/', confirme_reservation, name='confirme_reservation'),
    path('confirmt/', confirmt, name='confirmt'),
    #path('register/user/', register_user, name='register_user'),
    #path('register/superuser/', register_superuser, name='register_superuser'),
    # path('destination/<int:destination_id>/',destination,name='destination'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

compte/urls.py
from django.urls import path
from compte.views import*
from . import views
urlpatterns = [
    path('connecte/',connecte, name='connecte'),
    path('deconnecte/',deconnecte, name='deconnecte'),
    path('register_user/',register_user, name='register_user'),
    path('utilisateur/', views.ListeUtilisateurs.as_view(), name='liste_utilisateurs'),
    path('utilisateur/<int:pk>/', views.DetailUtilisateur.as_view(), name='detail_utilisateur'),
    path('utilisateur/<int:pk>/editer/', views.EditerUtilisateur.as_view(), name='editer_utilisateur'),
    path('utilisateur/<int:pk>/supprimer/', views.SupprimerUtilisateur.as_view(), name='supprimer_utilisateur'),

]

angaapp/models.py
#from django.contrib.auth.models import AbstractUser, BaseUserManager
#from django.contrib.auth.models import Group,Permission
#from django.utils.translation import gettext_lazy as _
#from django.core import validators
from django.db import models
import datetime
from twilio.rest import Client

class Pays (models.Model):
    nom=models.CharField(max_length=80)
    class Meta:
        verbose_name=("Pays")
        verbose_name_plural=("Pays")
    def __str__(self):
        return self.nom

class Ville(models.Model):
    pays=models.ForeignKey(Pays, on_delete=models.CASCADE)
    nom=models.CharField(max_length=40)
    date_created= models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = ("Ville")
        verbose_name_plural = ("Villes")
    def __str__(self):
        return self.nom
    
class Quartie(models.Model):
    ville=models.ForeignKey(Ville, on_delete=models.CASCADE)
    nom=models.CharField(max_length=80, blank=True)
    date_created=models.DateField(auto_now_add=True)
    def __str__(self):
        return self.nom


    
class Ligne(models.Model):
    villedp=models.ForeignKey(Ville, related_name='lignes_dp', on_delete=models.CASCADE)
    villearv=models.ForeignKey(Ville, related_name='lignes_arv', on_delete=models.CASCADE)
    date_created=models.DateField(auto_now_add=True)
    def __str__(self):
        return f"{self.villedp.nom} - {self.villearv.nom}"
    
    
class Societe(models.Model):
    ville=models.ForeignKey(Ville, on_delete=models.CASCADE)
    nom=models.CharField(max_length=80, blank=True)
    img = models.FileField(upload_to='societe_images/')

    create_date=models.DateField(auto_now_add=True)
    class Meta:
        verbose_name=('Societe')
        verbose_name_plural=('Societes')
    def __str__(self):
        return self.nom
    
    
class Heure_d(models.Model):
    
    time = models.TimeField()

    def __str__(self):
        return self.time.strftime('%H:%M:%S')  # Formatage de l'heure pour l'affichage

    
class Depart(models.Model):
    societe = models.ForeignKey(Societe, on_delete=models.CASCADE)
    ligne = models.ForeignKey(Ligne, on_delete=models.CASCADE)
    quartie = models.ForeignKey(Quartie, on_delete=models.CASCADE)
    car = models.CharField(max_length=10, choices=[('VIP', 'VIP'), ('Standard', 'Standard')])
    time = models.ForeignKey(Heure_d, on_delete=models.CASCADE)
    prix = models.DecimalField(max_digits=10, decimal_places=2)  # Champ prix
    create_date= models.DateField(auto_now_add=True)
    def __str__(self):
        return f"{self.ligne}"
    
class Reservations(models.Model):
    MODE_PAIEMENT_CHOICES = (
        ('orange_money', 'Orange Money'),
        ('moov_money', 'Moov Money'),
    )
    
    code_reservation = models.CharField(max_length=100, unique=True, editable=False)
    societe=models.ManyToManyField(Societe,)
    tel=models.CharField(max_length=80, blank=True)
    numero_cnib=models.CharField(max_length=60, null=True,blank=True)
    datedl_cnib=models.CharField(max_length=60, null=True,blank=True)
    nom=models.CharField(max_length=80, blank=True)
    prenom=models.CharField(max_length=80, blank=True)
    date=models.DateField()
    time=models.ForeignKey(Heure_d, on_delete=models.CASCADE)
    ligne=models.ForeignKey(Ligne, on_delete=models.CASCADE)
    car = models.CharField(max_length=10, choices=[('VIP', 'VIP'), ('Standard', 'Standard')])
    quartie=models.ForeignKey(Quartie, on_delete=models.CASCADE)
    mode_paiement = models.CharField(max_length=20, choices=MODE_PAIEMENT_CHOICES,null=True, blank=True)
    num_trans=models.CharField(max_length=80, blank=True)
    confirm = models.BooleanField(default=False)
    val = models.BooleanField(default=False)
    create_date= models.DateField(auto_now_add=True)
    
    class Meta:
            
            verbose_name =('Reservation')
            verbose_name_plural=('Reservations')
            db_table='reservations'
            ordering = ['-create_date']
    def generate_code(self):
        date_part = datetime.datetime.now().strftime("%d%m%Y")
        last_reservation = Reservations.objects.order_by('-id').first()
        if last_reservation:
            last_code_reservation = int(last_reservation.code_reservation[-1])
            new_code_reservation = last_code_reservation + 1
        else:
            new_code_reservation = 1
        code_reservation = f"{self.prenom[:1]}{self.nom[:1]}{date_part}{str(new_code_reservation).zfill(4)}"
        return code_reservation
    def save(self, *args, **kwargs):
        if not self.code_reservation:
            self.code_reservation = self.generate_code()
        super().save(*args, **kwargs)
    def __str__(self):
        return f"{self.nom} {self.prenom}"
class Confirme(models.Model):
    reservation = models.ManyToManyField(Reservations,)
    num_trans=models.CharField(max_length=80,)
    trans_id= models.CharField(max_length=150,)
    montant_paye = models.ForeignKey(Depart, on_delete=models.CASCADE)
    date_paiement = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.num_trans
class Valide(models.Model):
    confirmation = models.ManyToManyField(Confirme,)
    numticket = models.CharField(max_length=80,)
    numchaise = models.CharField(max_length=80, null=True, blank=True)
    def __str__(self):
        return self.numticket
    
from django.db import models

class SMS(models.Model):
    body = models.TextField()
    phone_number = models.CharField(max_length=20)
    timestamp = models.DateTimeField(auto_now_add=True)

angaapp/templates/affavalid.html
{% extends 'base.html' %}

{% block content %}
{% for societe in societe %}
    
    
<div class="col-md-6 col-lg-2 col-xlg-3">
  <a href="{% url 'affdes' societe.id %}">
  <div class="card card-hover">
    <div class="box bg-cyan text-center">
        
        <img class="card-img-top" src="{{societe.img.url}}" alt="Card image cap" >
        <div class="card-body">
            <h4 class="card-title mb-3">{{societe.nom}}</h4>
            <p class="card-text">
            </p>
        </div>
    </div>
  </div>
  </a>
</div>
{% endfor %}
{% endblock  %}

angaapp/templates/affdesti.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 col-lg-4 col-xlg-3">
    {% for destination in destination %}
    <a href="{% url 'affavalid' destination.id %}">
    <div class="card card-hover">
      <div class="box bg-success text-center">
        <h1 class="font-light text-white">
          <i class="mdi mdi-chart-areaspline"></i>
        </h1>
        <h6 class="text-white">{{ destination.nom}}</h6>
      </div>
    </div>
  </a>
  {% endfor%}
  </div>
{% endblock  %}

angaapp/templates/affdestination.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-12">
  <div class="card">
    <form method="post" action="{% url 'addligne'%}" class="form-horizontal">
      {% csrf_token %}
      <div class="card-body">
    <form method="post" action="{% url 'addheure'%}" class="form-horizontal">
      {% csrf_token %}
      <div class="card-body">
        <h4 class="card-title">HEURE</h4>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="time">HEURE</label>
          <div class="col-sm-9">
            <input type="time" name="time" class="form-control" id="nom" placeholder="Nom"/>
          </div>
        </div>
        <div class="border-top">
          <div class="card-body">
            <button type="Submit" class="btn btn-primary">Ajouter</button>
          </div>
        </div>
      </div>
    </form>

    <form method="post" action="{% url 'addepart'%}" class="form-horizontal">
      {% csrf_token %}
      <div class="card-body">
        <h4 class="card-title">Depart</h4>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label">Ville</label>
          <div class="col-sm-9">
              <input type="checkbox" id="bobo-checkbox" name="bobo-checkbox" value="bobo" onclick="checkUncheck('bobo-checkbox', 'ouaga-checkbox')">
              <label for="bobo-checkbox">Bobo-Dioulasso</label>
              <input type="checkbox" id="ouaga-checkbox" name="ouaga-checkbox" value="ouaga" onclick="checkUncheck('ouaga-checkbox', 'bobo-checkbox')">
              <label for="ouaga-checkbox">Ouagadougou</label>
          </div>
      </div>
        
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="societe">Sociéte</label>
          <div class="col-sm-9">
            <select id="societe-select" name="societe" class="form-control" required>
              {% for societe in societe %}
              <option value="{{societe.id}}">{{societe.nom }}-{{societe.ville}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="destination">Ligne</label>
          <div class="col-sm-9">
            <select name="ligne" id="ligne-select" class="form-control" required>
              {% for ligne in ligne %}
              <option value="{{ligne.id}}">{{ligne.villedp }}-{{ligne.villearv}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="destination">Quartie</label>
          <div class="col-sm-9">
            <select name="quartie" id="quartie-select" class="form-control" required>
              {% for quartie in quartie %}
              <option value="{{quartie.id}}">{{quartie.nom }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="car">CAR</label>
          <div class="col-sm-9">
            <select name="car" id="id_car" class="form-control" required>
              <option>--SELECTION CAR--</option>
              <option value="VIP">VIP</option>
              <option value="Standard">Standard</option>
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="destination">HEURE</label>
          <div class="col-sm-9">
            <select name="time" class="form-control" required>
              {% for time in time %}
              <option value="{{time.id}}">{{time.time|time:"H:i"}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 text-end control-label col-form-label" for="prix">Prix</label>
          <div class="col-sm-9">
              <input type="number" name="prix" id="prix" class="form-control" required>
          </div>
      </div>
        <div class="border-top">
          <div class="card-body">
            <button type="Submit" class="btn btn-primary">Ajouter</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function() {
      var boboCheckbox = document.getElementById("bobo-checkbox");
      var ouagaCheckbox = document.getElementById("ouaga-checkbox");
      var societeSelect = document.getElementById("societe-select");

      // Fonction pour charger les sociétés via une requête AJAX
      function loadSocietes(ville) {
          // Effectuez votre requête AJAX pour récupérer les sociétés correspondantes à la ville
          // Assurez-vous d'ajuster l'URL et les données de la requête en fonction de votre configuration Django
          var url = "{% url 'load_societes' %}?ville=" + ville;

          fetch(url)
              .then(response => response.json())
              .then(data => {
                  // Effacez les options existantes
                  societeSelect.innerHTML = "";

                  // Ajoutez les nouvelles options de société
                  data.forEach(societe => {
                      var option = document.createElement("option");
                      option.value = societe.id;
                      option.textContent = societe.nom + " - " + societe.ville;
                      societeSelect.appendChild(option);
                  });
              })
              .catch(error => console.error("Erreur lors du chargement des sociétés :", error));
      }

      // Vérifier l'état initial des cases à cocher lors du chargement de la page
      if (boboCheckbox.checked) {
          loadSocietes("Bobo-Dioulasso");
      } else if (ouagaCheckbox.checked) {
          loadSocietes("Ouagadougou");
      } else {
          // Effacez le contenu du select si aucun des deux n'est coché
          societeSelect.innerHTML = "";
      }

      // Écouteur d'événements pour les cases à cocher
      boboCheckbox.addEventListener("change", function() {
          if (boboCheckbox.checked) {
              loadSocietes("Bobo-Dioulasso");
          } else if (!ouagaCheckbox.checked) {
              // Effacez le contenu du select si aucun des deux n'est coché
              societeSelect.innerHTML = "";
          }
      });

      ouagaCheckbox.addEventListener("change", function() {
          if (ouagaCheckbox.checked) {
              loadSocietes("Ouagadougou");
          } else if (!boboCheckbox.checked) {
              // Effacez le contenu du select si aucun des deux n'est coché
              societeSelect.innerHTML = "";
          }
      });
  });
</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
      var boboCheckbox = document.getElementById("bobo-checkbox");
      var ouagaCheckbox = document.getElementById("ouaga-checkbox");
      var quartieSelect = document.getElementById("quartie-select");

      // Fonction pour charger les quartiers via une requête AJAX
      function loadQuarties(ville) {
          // Effectuez votre requête AJAX pour récupérer les quartiers correspondants à la ville
          // Assurez-vous d'ajuster l'URL et les données de la requête en fonction de votre configuration Django
          var url = "{% url 'load_quarties' %}?ville=" + ville;

          fetch(url)
              .then(response => response.json())
              .then(data => {
                  // Effacez les options existantes
                  quartieSelect.innerHTML = "";

                  // Ajoutez les nouvelles options de quartier
                  data.forEach(quartie => {
                      var option = document.createElement("option");
                      option.value = quartie.id;
                      option.textContent = quartie.nom;
                      quartieSelect.appendChild(option);
                  });
              })
              .catch(error => console.error("Erreur lors du chargement des quartiers :", error));
      }

      // Vérifier l'état initial des cases à cocher lors du chargement de la page
      if (boboCheckbox.checked) {
          loadQuarties("Bobo-Dioulasso");
      } else if (ouagaCheckbox.checked) {
          loadQuarties("Ouagadougou");
      } else {
          // Effacez le contenu du select si aucun des deux n'est coché
          quartieSelect.innerHTML = "";
      }

      // Écouteur d'événements pour les cases à cocher
      boboCheckbox.addEventListener("change", function() {
          if (boboCheckbox.checked) {
              loadQuarties("Bobo-Dioulasso");
          } else if (!ouagaCheckbox.checked) {
              // Effacez le contenu du select si aucun des deux n'est coché
              quartieSelect.innerHTML = "";
          }
      });

      ouagaCheckbox.addEventListener("change", function() {
          if (ouagaCheckbox.checked) {
              loadQuarties("Ouagadougou");
          } else if (!boboCheckbox.checked) {
              // Effacez le contenu du select si aucun des deux n'est coché
              quartieSelect.innerHTML = "";
          }
      });
  });
</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var boboCheckbox = document.getElementById("bobo-checkbox");
    var ouagaCheckbox = document.getElementById("ouaga-checkbox");
    var ligneSelect = document.getElementById("ligne-select");

    function loadLignes(ville) {
      var url = "{% url 'load_lignes' %}?ville=" + ville;

      fetch(url)
        .then(response => response.json())
        .then(data => {
          ligneSelect.innerHTML = ""; // Effacez les options existantes

          data.forEach(ligne => {
            var option = document.createElement("option");
            option.value = ligne.id;
            option.textContent = ville + "-" + ligne.villearv;
            ligneSelect.appendChild(option);
          });
        })
        .catch(error => console.error("Erreur lors du chargement des lignes :", error));
    }

    function clearLigneSelect() {
      ligneSelect.innerHTML = ""; // Effacez le contenu du select
    }

    boboCheckbox.addEventListener("change", function() {
      if (boboCheckbox.checked) {
        loadLignes("Bobo-Dioulasso");
      } else if (!ouagaCheckbox.checked) {
        clearLigneSelect();
      }
    });

    ouagaCheckbox.addEventListener("change", function() {
      if (ouagaCheckbox.checked) {
        loadLignes("Ouagadougou");
      } else if (!boboCheckbox.checked) {
        clearLigneSelect();
      }
    });

    // Vérifiez l'état initial des cases à cocher lors du chargement de la page
    if (!boboCheckbox.checked && !ouagaCheckbox.checked) {
      clearLigneSelect();
    }
  });
</script>


<script>
  function checkUncheck(checkedId, uncheckedId) {
      var checkedCheckbox = document.getElementById(checkedId);
      var uncheckedCheckbox = document.getElementById(uncheckedId);

      if (checkedCheckbox.checked) {
          uncheckedCheckbox.checked = false; // Décocher l'autre case à cocher
      }
  }
</script>



{% endblock  %}

angaapp/templates/affeditquartie.html
{% extends 'base.html' %}


{% block content %}
<div class="col-md-12">
    <div class="card">
      <form method="post" action="{% url 'updatekartie' quartie.id%}" class="form-horizontal">
        {% csrf_token %}
        <div class="card-body">
          <h4 class="card-title">Modifie Quartie</h4>
          <div class="form-group row">
            <label class="col-sm-3 text-end control-label col-form-label" for="ville">Ville</label>
            <div class="col-sm-9">
              <select name="ville" class="form-control" required>
                {% for ville_option in ville %}
                <option value="{{ ville_option.id }}" {% if ville_option.id == quartie.ville.id %}selected{% endif %}>{{ ville_option.nom }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="nom" class="col-sm-3 text-end control-label col-form-label">NOM</label>
            <div class="col-sm-9">
              <input type="text" name="nom" class="form-control" id="nom" placeholder="Nom" value="{{quartie.nom}}" required/>
            </div>
          </div>
          <div class="border-top">
            <div class="card-body">
              <button type="Submit" class="btn btn-primary">Ajouter</button>
            </div>
          </div>
        </div>
      </form>
    </div>
</div>
{% endblock %}
    

angaapp/templates/affkartie.html
{% extends 'base.html' %}


{% block content %}
<div class="col-md-12">
    <div class="card">
      <form method="post" action="{% url 'addkartie'%}" class="form-horizontal">
        {% csrf_token %}
        <div class="card-body">
          <h4 class="card-title">Quartie</h4>
          <div class="form-group row">
            <label class="col-sm-3 text-end control-label col-form-label" for="ville">Ville</label>
            <div class="col-sm-9">
              <select name="ville" class="form-control" required>
                {% for ville in ville %}
                <option value="{{ville.id}}">{{ville.nom }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="nom" class="col-sm-3 text-end control-label col-form-label">NOM</label>
            <div class="col-sm-9">
              <input type="text" name="nom" class="form-control" id="nom" placeholder="Nom" required/>
            </div>
          </div>
          <div class="border-top">
            <div class="card-body">
              <button type="Submit" class="btn btn-primary">Ajouter</button>
            </div>
          </div>
        </div>
      </form>
    </div>
</div>


<div class="row">
    <!-- Première moitié du card -->
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3>Quartie</h3>
          <div class="table-responsive">
            <table class="table">
              <!-- Entêtes de colonnes -->
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">ville</th>
                  <th scope="col">Nom du Quartie</th>
                </tr>
              </thead>
              <!-- Corps du tableau -->
              <tbody>
                {% for quartie in quartie_page %}
                <tr>
                  <td>#</td>
                  <td>{{ quartie.ville }}</td>
                  <td>{{ quartie.nom }}</td>
                  <td>
                    <a href="{% url 'deletequartie' quartie.id %}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?')" class="btn btn-outline-danger"><i class="me-2 mdi mdi-delete"></i></a>
                </td>
                <td>
                  <a href="{% url 'affeditquartie' quartie.id %}" onclick="return confirm('Êtes-vous sûr de vouloir Modifier cet élément ?')" class="btn btn-outline-info"><i class="me-2 mdi mdi-grease-pencil"></i></a>
                </td>    
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- Pagination -->
          <div class="pagination">
            {% if quartie_page.has_previous %}
            <a href="?quartie_page=1">Première</a>
            <a href="?quartie_page={{ quartie_page.previous_page_number }}" class="btn btn-outline-info">Précédent</a>
            {% endif %}
            <span class="current">Page {{ quartie_page.number }} de {{ quartie_page.paginator.num_pages }}.</span>
            {% if quartie_page.has_next %}
            <a href="?quartie_page={{ quartie_page.next_page_number }}" class="btn btn-outline-info">Suivant</a>
            <a href="?quartie_page={{ quartie_page.paginator.num_pages }}" class="btn btn-outline-info">Dernière</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% endblock  %}
    

angaapp/templates/confirme.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6">
    <div class="card">
      <form method="post" action="{% url 'confirme' reservation.id %}" class="form-horizontal">
        {% csrf_token %}
        <div class="card-body">
          <h4 class="card-title">Valide la Reservation</h4>
          <div class="form-group row">
            <label
              for="nom"
              class="col-sm-3 text-end control-label col-form-label"
              >num_trans</label>
            <div class="col-sm-9">
              <input
                type="text"
                name="num_trans"
                class="form-control"
                id="num_trans"
                placeholder="Numero de transfer"
              />
            </div>
          </div>
          <div class="form-group row">
            <label
              for="trans_id"
              class="col-sm-3 text-end control-label col-form-label"
              >Id du Transfer</label
            >
            <div class="col-sm-9">
              <input
                type="text"
                name="trans_id"
                class="form-control"
                id="trans_id"
                placeholder="id du transfer"
              />
            </div>
          </div>
          <div class="form-group row">
            <label
              for="date"
              class="col-sm-3 text-end control-label col-form-label"
              >montant_paye</label
            >
            <div class="col-sm-9">
              <input
                type="text"
                name="montant_paye"
                class="form-control"
                id="date"
                placeholder="Montant"
              />
            </div>
          </div>
          
        <div class="border-top">
          <div class="card-body">
            <button type="Submit" class="btn btn-outline-success">
              Valide
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock  %}